### ISSUE TITLE
Usage error

### ISSUE THREAD

**Issue by nowrap** [subarroca/ng2-kw-gauge#1]
Hello,
i am trying to use the module in my ionic 2 app.

I've installed it according the docs:
`npm install ng2-kw-gauge -S`

In the app.module.ts i added:
`import { GaugeModule, GaugeSegment, GaugeLabel } from 'ng2-kw-gauge';`
`@NgModule({
  imports: [
    IonicModule.forRoot(MyApp),
    GaugeModule, GaugeSegment, GaugeLabel
  ],`

The template.html looks like:
`<ng2-kw-gauge></ng2-kw-gauge>`

But i get a browser error:
`Error: Cannot find module "ng2-kw-gauge"`

Maybe someone can point me in the correct direction what i'am doing wrong?

**Comment by subarroca** [comment]
You should not declare GaugeLabel nor GaugeSegment in your module, only where you're gonna use it. 

Also if you are using system.js you should map it there too. 

That's the only thing I see wrong right now.

**Comment by nowrap** [comment]
Thx for your answer. A system.js i don't have.

I redirected the question to the ionic forum. Maybe it's an ionic specific "mapping" thing.

**Comment by subarroca** [comment]
Perfect, just let me know

**Comment by nowrap** [comment]
Today, it worked ...
Only the gauge.component.scss couldn't be loaded. I had to copy it to the www directory.

**Comment by subarroca** [comment]
It's weird. I'll check again in my code if scss is loading

**Comment by subarroca** [comment]
I can confirm it's working

**Comment by Tyler-Darby** [comment]
@nowrap @subarroca  Can you guys post a full example? I'm having trouble getting it to work too

**Comment by Tyler-Darby** [comment]
Here's my error that I am getting:
```Uncaught Error: Module build failed: TypeError: Cannot read property 'content' of undefined
    at Object.typescriptSourcemapLoaderMemory```

**Comment by subarroca** [comment]
Hi @Tyler-Darby could you specify the version of angular you're using and if it's combined with ionic?

**Comment by Tyler-Darby** [comment]
@subarroca I got it working, It was excluded in my tsconfig.json for some reason, all good now. Awesome little component you've got here 👍

**Comment by zjw1918** [comment]
@Tyler-Darby hi, Having the same problem, "Cannot read property 'content' of undefined", how do you solve that, thanks.

**Comment by Tyler-Darby** [comment]
@zjw1918 Are you using Ionic?

I made this tweak to my `tsconfig.json` file.
```
  "include": [
    "src/**/*.ts",
    "node_modules/ng2-kw-gauge/index.ts"
  ],
```

**Comment by subarroca** [comment]
Thanks @Tyler-Darby
