### ISSUE TITLE
IE11 Support

### ISSUE THREAD

**Issue by Tomagi** [subarroca/ng2-kw-gauge#5]
Hi,
It seems it doesn't work well in Internet Explorer 11 (visibility + animations).

Any idea how to fix..?

10X.

**Comment by subarroca** [comment]
As referred here: https://connect.microsoft.com/IE/feedbackdetail/view/920928/ie-11-css-transition-property-not-working-for-svg-elements

IE11 has lots of issues with animation of properties. What started as a raised flag for fill property was later extended to stroke, etc. Thus animation in IE11 would require doing it via js.

Transform on SVG is not allowed either, I'll try to improve this part but not the animation. If you want you can try to implement that part and if that keeps clean for other browsers I can merge the PR

**Comment by subarroca** [comment]
Positioning is fixed in 0.0.8 but animation is discarded, as it may add unnecessary complexity for the rest of the browsers
